language: rust

jobs:
  include:
    - rust: stable
      env: RUSTFMTCHECK=true
    - rust: nightly
    - rust: 1.29.0
    # Integration tests
    - rust: stable
      env: BITCOINVERSION=0.18.0
    - rust: stable
      env: BITCOINVERSION=0.18.1
    - rust: stable
      env: BITCOINVERSION=0.19.0.1
    - rust: stable
      env: BITCOINVERSION=0.19.1
    - rust: stable
      env: BITCOINVERSION=0.20.0
    - rust: stable
      env: BITCOINVERSION=0.20.1
    - rust: stable
      env: BITCOINVERSION=0.21.0
    - rust: stable
      env: BITCOINVERSION=22.0

script:
  - ./contrib/test.sh
